[package]
name = "ws-bridge"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
bytes.workspace = true
futures.workspace = true
futures-util.workspace = true
http.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
