[package]
name = "relay-hosts"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
chrono.workspace = true
axum.workspace = true
ed25519-dalek.workspace = true
futures-util.workspace = true
http.workspace = true
relay-client.workspace = true
relay-ws.workspace = true
relay-control.workspace = true
remote-info.workspace = true
relay-types.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
services.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
trusted-key-auth.workspace = true
url.workspace = true
utils.workspace = true
uuid.workspace = true
relay-webrtc.workspace = true
ws-bridge.workspace = true
tokio-util.workspace = true
base64.workspace = true
