[package]
name = "relay-tunnel-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
futures-util.workspace = true
http.workspace = true
hyper.workspace = true
hyper-util.workspace = true
rustls.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-util.workspace = true
tokio-yamux.workspace = true
tracing.workspace = true
ws-bridge.workspace = true
