[package]
name = "embedded-ssh"
version.workspace = true
edition.workspace = true

[dependencies]
russh.workspace = true
russh-keys.workspace = true
russh-sftp.workspace = true
ssh-key.workspace = true
ed25519-dalek.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
rand.workspace = true
tempfile.workspace = true
