[package]
name = "git"
version.workspace = true
edition.workspace = true

[features]
default = []
cloud = []

[dependencies]
chrono.workspace = true
dirs.workspace = true
git2.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
ts-rs.workspace = true
utils.workspace = true

[dev-dependencies]
tempfile.workspace = true
